name: Other CI

on:
  push:
    branches:
      - '!develop'
      - '!master'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI: true

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Init
      run: |
        version=$(sed "s/^    version=\"\(.*\)\",$/\1/;t;d" setup.py)
        echo "Version: "$version
        if [[ ! $version =~ "SNAPSHOT" ]]; then
          echo ERROR: Wrong version 1>&2
          exit 1
        fi
      working-directory: ${{ env.working-directory }}

    - name: Test
      run: make test
      working-directory: ${{ env.working-directory }}
